extends: [[spectral:oas, all]]

rules:
  # Enforce ubiquitous language - use "partner" not "customer"
  ubiquitous-language-partner:
    description: Use 'partner' instead of 'customer' in API paths and descriptions
    message: "{{error}} - Use 'partner' instead of 'customer' to maintain ubiquitous language"
    severity: error
    given: "$..paths..*~"
    then:
      function: pattern
      functionOptions:
        notMatch: "/customer"
  
  ubiquitous-language-application:
    description: Use 'application' instead of 'request' for onboarding applications
    message: "Use 'application' instead of 'request' for onboarding applications"
    severity: warn
    given: "$..paths..*~"
    then:
      function: pattern
      functionOptions:
        notMatch: "/request"
  
  # Enforce major-only versioning (v1, v2, not v1.2)
  major-version-only:
    description: API paths must use major versions only (/v1/, /v2/), not minor versions
    message: "{{path}} - Use major versions only (e.g., /v1/, /v2/), not /v1.2/"
    severity: error
    given: "$..paths.*~"
    then:
      function: pattern
      functionOptions:
        notMatch: "/v\\d+\\.\\d+"
  
  # Enforce lowercase paths with hyphens
  path-lowercase-hyphen:
    description: Paths must be lowercase with hyphens (kebab-case)
    message: "{{path}} - Use lowercase with hyphens (e.g., /work-items not /WorkItems)"
    severity: error
    given: "$..paths.*~"
    then:
      function: pattern
      functionOptions:
        match: "^(/[a-z0-9-/{}]+|/)$"
  
  # Enforce plural resource names
  path-plural-resources:
    description: Resource names should be plural
    message: "{{path}} - Use plural resource names (e.g., /applications not /application)"
    severity: warn
    given: "$..paths.*~"
    then:
      - function: pattern
        functionOptions:
          notMatch: "/v\\d+/[a-z]+-[a-z]+$"  # Don't match paths ending with singular
  
  # Require operation IDs
  operation-operationId:
    description: All operations must have an operationId
    message: "Missing operationId for {{path}}"
    severity: error
    given: "$..paths..operations[*]"
    then:
      field: operationId
      function: truthy
  
  # Require operation descriptions
  operation-description:
    description: All operations must have a description
    message: "Missing description for {{path}}"
    severity: warn
    given: "$..paths..operations[*]"
    then:
      field: description
      function: truthy
  
  # Require response examples
  response-examples:
    description: 200 responses should include examples
    message: "Missing example for 200 response in {{path}}"
    severity: warn
    given: "$..paths..responses.200"
    then:
      field: content..example
      function: truthy
  
  # Enforce standard error responses
  standard-error-responses:
    description: Operations should define 400, 401, 404, 500 error responses
    message: "Missing standard error responses (400, 401, 404, 500) for {{path}}"
    severity: warn
    given: "$..paths..operations[*]"
    then:
      field: responses
      function: schema
      functionOptions:
        schema:
          type: object
          required: ["400", "401", "500"]
  
  # Require security schemes
  security-defined:
    description: Operations must have security defined
    message: "{{path}} - Missing security definition"
    severity: error
    given: "$..paths..operations[*]"
    then:
      field: security
      function: truthy
  
  # Enforce request ID header
  request-id-header:
    description: Operations should document X-Request-Id header
    message: "{{path}} - Document X-Request-Id header for traceability"
    severity: warn
    given: "$..paths..operations[*]"
    then:
      field: parameters
      function: schema
      functionOptions:
        schema:
          type: array
          contains:
            properties:
              name:
                const: X-Request-Id
  
  # Deprecation warning
  no-deprecated-without-sunset:
    description: Deprecated endpoints must have Sunset header documented
    message: "{{path}} - Deprecated endpoint must document Sunset header"
    severity: error
    given: "$..paths..operations[?(@.deprecated == true)]"
    then:
      field: responses..headers.Sunset
      function: truthy
  
  # Pagination standard
  pagination-parameters:
    description: List operations should use standard pagination (page, pageSize)
    message: "{{path}} - Use standard pagination parameters (page, pageSize)"
    severity: warn
    given: "$..paths..get.parameters"
    then:
      function: schema
      functionOptions:
        schema:
          type: array
          contains:
            anyOf:
              - properties:
                  name:
                    const: page
              - properties:
                  name:
                    const: pageSize
  
  # Rate limiting headers
  rate-limit-headers:
    description: Rate-limited endpoints should document rate limit headers
    message: "{{path}} - Document X-RateLimit-* headers"
    severity: info
    given: "$..paths..operations[*].responses.429"
    then:
      field: headers
      function: schema
      functionOptions:
        schema:
          type: object
          required: ["X-RateLimit-Limit", "X-RateLimit-Remaining", "X-RateLimit-Reset"]
  
  # ETag for GET operations
  etag-for-resources:
    description: Resource GET operations should support ETag
    message: "{{path}} - Consider adding ETag header for caching"
    severity: info
    given: "$..paths..get.responses.200"
    then:
      field: headers.ETag
      function: truthy
  
  # Content-Type validation
  content-type-required:
    description: Request bodies must specify content type
    message: "{{path}} - Specify Content-Type for request body"
    severity: error
    given: "$..paths..requestBody.content"
    then:
      function: truthy
