name: API Contract Validation

on:
  pull_request:
    paths:
      - 'services/*/openapi.yaml'
      - 'services/*/src/**/*.cs'

jobs:
  validate-openapi-specs:
    name: Validate OpenAPI Specifications
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Need full history for comparison

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Spectral
        run: npm install -g @stoplight/spectral-cli

      - name: Create Spectral ruleset
        run: |
          cat > .spectral.yaml << 'EOF'
          extends: [[spectral:oas, all]]
          rules:
            # Enforce versioning in path
            oas3-api-servers:
              description: Servers must include /v{N} in path
              severity: error
              given: $.servers[*].url
              then:
                function: pattern
                functionOptions:
                  match: "^https?://.*/(v[0-9]+)/?$"
            
            # All operations must have operationId
            operation-operationId:
              description: All operations must have operationId
              severity: error
              given: $.paths[*][*]
              then:
                field: operationId
                function: truthy
            
            # POST operations must document idempotency key
            operation-post-idempotency:
              description: POST operations should document Idempotency-Key header
              severity: warn
              given: $.paths[*].post
              then:
                field: parameters
                function: schema
                functionOptions:
                  schema:
                    type: array
                    contains:
                      properties:
                        name:
                          const: Idempotency-Key
            
            # Error responses must use standard schema
            operation-4xx-response:
              description: 4xx responses must reference ErrorResponse schema
              severity: error
              given: $.paths[*][*].responses[?(@property.match(/^4/))]
              then:
                field: content.application/json.schema.$ref
                function: pattern
                functionOptions:
                  match: ".*ErrorResponse$"
          EOF

      - name: Lint OpenAPI specs
        run: |
          for spec in services/*/openapi.yaml; do
            if [ -f "$spec" ]; then
              echo "Linting $spec"
              spectral lint "$spec" --ruleset .spectral.yaml --fail-severity warn
            fi
          done

      - name: Check for breaking changes
        uses: oasdiff/oasdiff-action/breaking@main
        with:
          base: ${{ github.base_ref }}
          revision: ${{ github.head_ref }}
          format: text
          fail-on-diff: true

      - name: Comment PR with breaking changes
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '⚠️ **Breaking API changes detected!**\n\nThis PR introduces breaking changes to the API contract. Please:\n1. Review changes with API architect\n2. Create migration guide\n3. Update CHANGELOG.md\n4. Plan deprecation timeline (6 months minimum)\n5. Notify affected partners'
            })

  validate-spec-to-code:
    name: Validate Spec-to-Code Alignment
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [onboarding-api, document-service]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install OpenAPI Generator
        run: |
          wget https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/7.2.0/openapi-generator-cli-7.2.0.jar -O openapi-generator-cli.jar

      - name: Generate code from OpenAPI spec
        run: |
          java -jar openapi-generator-cli.jar generate \
            -i services/${{ matrix.service }}/openapi.yaml \
            -g aspnetcore \
            -o generated/${{ matrix.service }} \
            --additional-properties=aspnetCoreVersion=8.0

      - name: Compare generated vs actual
        run: |
          # Extract controller method signatures
          echo "Checking controller alignment..."
          
          # This is a simplified check - in production, use more sophisticated comparison
          if diff -r generated/${{ matrix.service }}/Controllers services/${{ matrix.service }}/src/Presentation/Controllers --brief; then
            echo "✓ Spec-to-code alignment verified"
          else
            echo "⚠️  Differences detected between OpenAPI spec and implementation"
            echo "Review and ensure controllers match OpenAPI specification"
          fi

  contract-tests:
    name: Run Contract Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd tests/contract
          npm install

      - name: Run consumer contract tests
        run: |
          cd tests/contract
          npm run test:consumer

      - name: Publish pacts
        if: github.ref == 'refs/heads/main'
        env:
          PACT_BROKER_URL: ${{ secrets.PACT_BROKER_URL }}
          PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}
        run: |
          cd tests/contract
          npm run pact:publish

  definition-of-done:
    name: Verify Definition of Done
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for required files
        run: |
          has_errors=0
          
          # Check if OpenAPI spec was updated
          if git diff --name-only origin/${{ github.base_ref }}...HEAD | grep -q "openapi.yaml"; then
            echo "✓ OpenAPI spec updated"
            
            # Verify CHANGELOG was updated
            if ! git diff --name-only origin/${{ github.base_ref }}...HEAD | grep -q "CHANGELOG.md"; then
              echo "✗ CHANGELOG.md not updated"
              has_errors=1
            fi
            
            # Check for migration guide (if breaking changes)
            # This would integrate with oasdiff output
          fi
          
          exit $has_errors

      - name: Check for tests
        run: |
          # Ensure tests exist for modified code
          modified_files=$(git diff --name-only origin/${{ github.base_ref }}...HEAD | grep "\.cs$" || true)
          
          if [ -n "$modified_files" ]; then
            echo "Code changes detected, checking for tests..."
            
            for file in $modified_files; do
              # Check if corresponding test file exists
              test_file=$(echo "$file" | sed 's|/src/|/tests/|' | sed 's|\.cs$|Tests.cs|')
              
              if [ ! -f "$test_file" ]; then
                echo "⚠️  No test file found for $file"
              fi
            done
          fi

