// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OnboardingApi.Infrastructure.Persistence.Projections;

#nullable disable

namespace OnboardingApi.Infrastructure.Migrations.Projections
{
    [DbContext(typeof(ProjectionsDbContext))]
    [Migration("20251119182603_InitialCreate_Projections")]
    partial class InitialCreate_Projections
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("projections")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OnboardingApi.Domain.Projections.ReadModels.OnboardingCaseProjection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApplicantAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("applicant_address");

                    b.Property<string>("ApplicantCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("applicant_city");

                    b.Property<string>("ApplicantCountry")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("applicant_country");

                    b.Property<DateTime?>("ApplicantDateOfBirth")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("applicant_date_of_birth");

                    b.Property<string>("ApplicantEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("applicant_email");

                    b.Property<string>("ApplicantFirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("applicant_first_name");

                    b.Property<string>("ApplicantLastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("applicant_last_name");

                    b.Property<string>("ApplicantNationality")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("applicant_nationality");

                    b.Property<string>("ApplicantPhone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("applicant_phone");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<string>("AssignedTo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("assigned_to");

                    b.Property<string>("AssignedToName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("assigned_to_name");

                    b.Property<string>("BusinessAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("business_address");

                    b.Property<decimal?>("BusinessAnnualRevenue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("business_annual_revenue");

                    b.Property<string>("BusinessCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("business_city");

                    b.Property<string>("BusinessCountryOfRegistration")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("business_country_of_registration");

                    b.Property<string>("BusinessIndustry")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("business_industry");

                    b.Property<string>("BusinessLegalName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("business_legal_name");

                    b.Property<int?>("BusinessNumberOfEmployees")
                        .HasColumnType("integer")
                        .HasColumnName("business_number_of_employees");

                    b.Property<string>("BusinessRegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("business_registration_number");

                    b.Property<string>("BusinessTaxId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("business_tax_id");

                    b.Property<string>("BusinessWebsite")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("business_website");

                    b.Property<string>("CaseId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("case_id");

                    b.Property<int>("ChecklistCompletedItems")
                        .HasColumnType("integer")
                        .HasColumnName("checklist_completed_items");

                    b.Property<int>("ChecklistCompletedRequiredItems")
                        .HasColumnType("integer")
                        .HasColumnName("checklist_completed_required_items");

                    b.Property<decimal>("ChecklistCompletionPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("checklist_completion_percentage");

                    b.Property<Guid?>("ChecklistId")
                        .HasColumnType("uuid")
                        .HasColumnName("checklist_id");

                    b.Property<int>("ChecklistRequiredItems")
                        .HasColumnType("integer")
                        .HasColumnName("checklist_required_items");

                    b.Property<string>("ChecklistStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("checklist_status");

                    b.Property<int>("ChecklistTotalItems")
                        .HasColumnType("integer")
                        .HasColumnName("checklist_total_items");

                    b.Property<int>("CompletedSteps")
                        .HasColumnType("integer")
                        .HasColumnName("completed_steps");

                    b.Property<string>("ComplianceNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("compliance_notes");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DocumentCount")
                        .HasColumnType("integer")
                        .HasColumnName("document_count");

                    b.Property<bool>("HasComplianceIssues")
                        .HasColumnType("boolean")
                        .HasColumnName("has_compliance_issues");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("PartnerId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("partner_id");

                    b.Property<string>("PartnerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("partner_name");

                    b.Property<string>("PartnerReferenceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("partner_reference_id");

                    b.Property<int>("PendingDocumentCount")
                        .HasColumnType("integer")
                        .HasColumnName("pending_document_count");

                    b.Property<decimal>("ProgressPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("progress_percentage");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rejected_at");

                    b.Property<int>("RejectedDocumentCount")
                        .HasColumnType("integer")
                        .HasColumnName("rejected_document_count");

                    b.Property<bool>("RequiresManualReview")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_manual_review");

                    b.Property<Guid?>("RiskAssessmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("risk_assessment_id");

                    b.Property<int>("RiskFactorCount")
                        .HasColumnType("integer")
                        .HasColumnName("risk_factor_count");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("risk_level");

                    b.Property<decimal>("RiskScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("risk_score");

                    b.Property<string>("RiskStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("risk_status");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<int>("TotalSteps")
                        .HasColumnType("integer")
                        .HasColumnName("total_steps");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("VerifiedDocumentCount")
                        .HasColumnType("integer")
                        .HasColumnName("verified_document_count");

                    b.HasKey("Id");

                    b.HasIndex("AssignedTo");

                    b.HasIndex("CaseId")
                        .IsUnique();

                    b.HasIndex("CreatedAt");

                    b.HasIndex("HasComplianceIssues");

                    b.HasIndex("PartnerId");

                    b.HasIndex("RequiresManualReview");

                    b.HasIndex("RiskLevel");

                    b.HasIndex("Status");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("AssignedTo", "Status", "CreatedAt");

                    b.HasIndex("PartnerId", "Status", "CreatedAt");

                    b.HasIndex("Status", "RiskLevel", "CreatedAt");

                    b.ToTable("onboarding_case_projections", "projections");
                });
#pragma warning restore 612, 618
        }
    }
}
