// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OnboardingApi.Infrastructure.Persistence;

#nullable disable

namespace OnboardingApi.Infrastructure.Migrations.Onboarding
{
    [DbContext(typeof(OnboardingDbContext))]
    partial class OnboardingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("onboarding")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OnboardingApi.Application.Commands.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AnonymizationReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("AnonymizedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ApplicantName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BankAccountNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdentificationNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAnonymized")
                        .HasColumnType("boolean");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TaxNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Applications", "onboarding");
                });

            modelBuilder.Entity("OnboardingApi.Domain.Aggregates.OnboardingCase", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CaseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("case_number");

                    b.Property<string>("ChecklistItems")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("checklist_items");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("created_by");

                    b.Property<string>("DocumentRequests")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("document_requests");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<Guid>("PartnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("partner_id");

                    b.Property<string>("PartnerReferenceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("partner_reference_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("CaseNumber")
                        .IsUnique();

                    b.HasIndex("PartnerId");

                    b.ToTable("onboarding_cases", "onboarding");
                });

            modelBuilder.Entity("OnboardingApi.Infrastructure.Persistence.OutboxEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_id");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("aggregate_type");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("event_type");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("Id");

                    b.HasIndex("AggregateId");

                    b.HasIndex("ProcessedAt", "OccurredAt")
                        .HasDatabaseName("idx_outbox_processed");

                    b.ToTable("outbox_events", "onboarding");
                });

            modelBuilder.Entity("OnboardingApi.Domain.Aggregates.OnboardingCase", b =>
                {
                    b.OwnsOne("OnboardingApi.Domain.ValueObjects.ApplicantDetails", "Applicant", b1 =>
                        {
                            b1.Property<Guid>("OnboardingCaseId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("DateOfBirth")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("applicant_date_of_birth");

                            b1.Property<string>("DriversLicenseNumber")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("applicant_drivers_license");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("applicant_email");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("applicant_first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("applicant_last_name");

                            b1.Property<string>("MiddleName")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("applicant_middle_name");

                            b1.Property<string>("Nationality")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("applicant_nationality");

                            b1.Property<string>("PassportNumber")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("applicant_passport_number");

                            b1.Property<string>("PhoneNumber")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("applicant_phone_number");

                            b1.Property<string>("TaxId")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("applicant_tax_id");

                            b1.HasKey("OnboardingCaseId");

                            b1.ToTable("onboarding_cases", "onboarding");

                            b1.WithOwner()
                                .HasForeignKey("OnboardingCaseId");

                            b1.OwnsOne("OnboardingApi.Domain.ValueObjects.Address", "ResidentialAddress", b2 =>
                                {
                                    b2.Property<Guid>("ApplicantDetailsOnboardingCaseId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("City")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("applicant_address_city");

                                    b2.Property<string>("Country")
                                        .IsRequired()
                                        .HasMaxLength(2)
                                        .HasColumnType("character varying(2)")
                                        .HasColumnName("applicant_address_country");

                                    b2.Property<string>("PostalCode")
                                        .IsRequired()
                                        .HasMaxLength(20)
                                        .HasColumnType("character varying(20)")
                                        .HasColumnName("applicant_address_postal_code");

                                    b2.Property<string>("State")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("applicant_address_state");

                                    b2.Property<string>("Street")
                                        .IsRequired()
                                        .HasMaxLength(255)
                                        .HasColumnType("character varying(255)")
                                        .HasColumnName("applicant_address_street");

                                    b2.Property<string>("Street2")
                                        .HasMaxLength(255)
                                        .HasColumnType("character varying(255)")
                                        .HasColumnName("applicant_address_street2");

                                    b2.HasKey("ApplicantDetailsOnboardingCaseId");

                                    b2.ToTable("onboarding_cases", "onboarding");

                                    b2.WithOwner()
                                        .HasForeignKey("ApplicantDetailsOnboardingCaseId");
                                });

                            b1.Navigation("ResidentialAddress")
                                .IsRequired();
                        });

                    b.OwnsOne("OnboardingApi.Domain.ValueObjects.BusinessDetails", "Business", b1 =>
                        {
                            b1.Property<Guid>("OnboardingCaseId")
                                .HasColumnType("uuid");

                            b1.Property<string>("BusinessType")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("business_type");

                            b1.Property<decimal>("EstimatedAnnualRevenue")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("business_estimated_annual_revenue");

                            b1.Property<DateTime>("IncorporationDate")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("business_incorporation_date");

                            b1.Property<string>("Industry")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("business_industry");

                            b1.Property<string>("LegalName")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("business_legal_name");

                            b1.Property<int>("NumberOfEmployees")
                                .HasColumnType("integer")
                                .HasColumnName("business_number_of_employees");

                            b1.Property<string>("RegistrationCountry")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("business_registration_country");

                            b1.Property<string>("RegistrationNumber")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("business_registration_number");

                            b1.Property<string>("TaxId")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("business_tax_id");

                            b1.Property<string>("TradeName")
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("business_trade_name");

                            b1.Property<string>("VatNumber")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("business_vat_number");

                            b1.Property<string>("Website")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("business_website");

                            b1.HasKey("OnboardingCaseId");

                            b1.ToTable("onboarding_cases", "onboarding");

                            b1.WithOwner()
                                .HasForeignKey("OnboardingCaseId");

                            b1.OwnsOne("OnboardingApi.Domain.ValueObjects.Address", "OperatingAddress", b2 =>
                                {
                                    b2.Property<Guid>("BusinessDetailsOnboardingCaseId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("City")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("business_operating_address_city");

                                    b2.Property<string>("Country")
                                        .IsRequired()
                                        .HasMaxLength(2)
                                        .HasColumnType("character varying(2)")
                                        .HasColumnName("business_operating_address_country");

                                    b2.Property<string>("PostalCode")
                                        .IsRequired()
                                        .HasMaxLength(20)
                                        .HasColumnType("character varying(20)")
                                        .HasColumnName("business_operating_address_postal_code");

                                    b2.Property<string>("State")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("business_operating_address_state");

                                    b2.Property<string>("Street")
                                        .IsRequired()
                                        .HasMaxLength(255)
                                        .HasColumnType("character varying(255)")
                                        .HasColumnName("business_operating_address_street");

                                    b2.Property<string>("Street2")
                                        .HasMaxLength(255)
                                        .HasColumnType("character varying(255)")
                                        .HasColumnName("business_operating_address_street2");

                                    b2.HasKey("BusinessDetailsOnboardingCaseId");

                                    b2.ToTable("onboarding_cases", "onboarding");

                                    b2.WithOwner()
                                        .HasForeignKey("BusinessDetailsOnboardingCaseId");
                                });

                            b1.OwnsOne("OnboardingApi.Domain.ValueObjects.Address", "RegisteredAddress", b2 =>
                                {
                                    b2.Property<Guid>("BusinessDetailsOnboardingCaseId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("City")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("business_registered_address_city");

                                    b2.Property<string>("Country")
                                        .IsRequired()
                                        .HasMaxLength(2)
                                        .HasColumnType("character varying(2)")
                                        .HasColumnName("business_registered_address_country");

                                    b2.Property<string>("PostalCode")
                                        .IsRequired()
                                        .HasMaxLength(20)
                                        .HasColumnType("character varying(20)")
                                        .HasColumnName("business_registered_address_postal_code");

                                    b2.Property<string>("State")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("business_registered_address_state");

                                    b2.Property<string>("Street")
                                        .IsRequired()
                                        .HasMaxLength(255)
                                        .HasColumnType("character varying(255)")
                                        .HasColumnName("business_registered_address_street");

                                    b2.Property<string>("Street2")
                                        .HasMaxLength(255)
                                        .HasColumnType("character varying(255)")
                                        .HasColumnName("business_registered_address_street2");

                                    b2.HasKey("BusinessDetailsOnboardingCaseId");

                                    b2.ToTable("onboarding_cases", "onboarding");

                                    b2.WithOwner()
                                        .HasForeignKey("BusinessDetailsOnboardingCaseId");
                                });

                            b1.Navigation("OperatingAddress");

                            b1.Navigation("RegisteredAddress")
                                .IsRequired();
                        });

                    b.Navigation("Applicant")
                        .IsRequired();

                    b.Navigation("Business");
                });
#pragma warning restore 612, 618
        }
    }
}
