---
# Document Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: document-service
  namespace: business-documents
spec:
  replicas: 1
  selector:
    matchLabels:
      app: document-service
  template:
    metadata:
      labels:
        app: document-service
    spec:
      containers:
      - name: document-service
        image: nginx:alpine
        ports:
        - containerPort: 80
        env:
        - name: SERVICE_NAME
          value: "document-service"
---
apiVersion: v1
kind: Service
metadata:
  name: document-service
  namespace: business-documents
spec:
  selector:
    app: document-service
  ports:
  - port: 80
    targetPort: 80
---
# Risk Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: risk-service
  namespace: business-risk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: risk-service
  template:
    metadata:
      labels:
        app: risk-service
    spec:
      containers:
      - name: risk-service
        image: nginx:alpine
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: risk-service
  namespace: business-risk
spec:
  selector:
    app: risk-service
  ports:
  - port: 80
    targetPort: 80
---
# Notification Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: business-notifications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: nginx:alpine
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: business-notifications
spec:
  selector:
    app: notification-service
  ports:
  - port: 80
    targetPort: 80
---
# Checklist Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checklist-service
  namespace: business-onboarding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checklist-service
  template:
    metadata:
      labels:
        app: checklist-service
    spec:
      containers:
      - name: checklist-service
        image: nginx:alpine
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: checklist-service
  namespace: business-onboarding
spec:
  selector:
    app: checklist-service
  ports:
  - port: 80
    targetPort: 80
