---
# Document Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kyc-document-api
  namespace: business-documents
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kyc-document-api
  template:
    metadata:
      labels:
        app: kyc-document-api
    spec:
      containers:
      - name: kyc-document-api
        image: nginx:alpine
        ports:
        - containerPort: 80
        env:
        - name: SERVICE_NAME
          value: "kyc-document-api"
---
apiVersion: v1
kind: Service
metadata:
  name: kyc-document-api
  namespace: business-documents
spec:
  selector:
    app: kyc-document-api
  ports:
  - port: 80
    targetPort: 80
---
# Risk Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kyc-risk-api
  namespace: business-risk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kyc-risk-api
  template:
    metadata:
      labels:
        app: kyc-risk-api
    spec:
      containers:
      - name: kyc-risk-api
        image: nginx:alpine
        ports:
        - containerPort: 80
        env:
        - name: SERVICE_NAME
          value: "kyc-risk-api"
---
apiVersion: v1
kind: Service
metadata:
  name: kyc-risk-api
  namespace: business-risk
spec:
  selector:
    app: kyc-risk-api
  ports:
  - port: 80
    targetPort: 80
---
# Notification Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kyc-notification-api
  namespace: business-notifications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kyc-notification-api
  template:
    metadata:
      labels:
        app: kyc-notification-api
    spec:
      containers:
      - name: kyc-notification-api
        image: nginx:alpine
        ports:
        - containerPort: 80
        env:
        - name: SERVICE_NAME
          value: "kyc-notification-api"
---
apiVersion: v1
kind: Service
metadata:
  name: kyc-notification-api
  namespace: business-notifications
spec:
  selector:
    app: kyc-notification-api
  ports:
  - port: 80
    targetPort: 80
---
# Checklist Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kyc-checklist-api
  namespace: business-onboarding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kyc-checklist-api
  template:
    metadata:
      labels:
        app: kyc-checklist-api
    spec:
      containers:
      - name: kyc-checklist-api
        image: nginx:alpine
        ports:
        - containerPort: 80
        env:
        - name: SERVICE_NAME
          value: "kyc-checklist-api"
---
apiVersion: v1
kind: Service
metadata:
  name: kyc-checklist-api
  namespace: business-onboarding
spec:
  selector:
    app: kyc-checklist-api
  ports:
  - port: 80
    targetPort: 80
