---
# Static React Frontend using nginx
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-static
  namespace: business-onboarding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-static
  template:
    metadata:
      labels:
        app: react-static
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: react-build
          mountPath: /usr/share/nginx/html
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      volumes:
      - name: react-build
        hostPath:
          path: /root/onboarding_kyc/frontend/mukuruKyc/dist/public
          type: Directory
      - name: nginx-config
        configMap:
          name: react-nginx-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: react-nginx-config
  namespace: business-onboarding
data:
  default.conf: |
    server {
        listen 80;
        server_name _;
        root /usr/share/nginx/html;
        index index.html;
        
        # Handle React Router
        location / {
            try_files $uri $uri/ /index.html;
        }
        
        # API proxy
        location /api/ {
            proxy_pass http://onboarding-api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        
        # Static assets
        location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
            expires 1y;
            add_header Cache-Control "public, immutable";
        }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: react-static
  namespace: business-onboarding
spec:
  selector:
    app: react-static
  ports:
  - port: 80
    targetPort: 80
