---
# Simple Kafka deployment using wurstmeister/kafka
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-simple
  namespace: platform-observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-simple
  template:
    metadata:
      labels:
        app: kafka-simple
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka:latest
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: "kafka-simple.platform-observability.svc.cluster.local"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper.platform-observability.svc.cluster.local:2181"
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_CREATE_TOPICS
          value: "onboarding.domain-events:1:1,onboarding.integration-events:1:1"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-simple
  namespace: platform-observability
spec:
  selector:
    app: kafka-simple
  ports:
  - port: 9092
    targetPort: 9092
