// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OnboardingApi.Infrastructure.Persistence.EntityConfiguration;

#nullable disable

namespace OnboardingApi.Infrastructure.Migrations.EntityConfiguration
{
    [DbContext(typeof(EntityConfigurationDbContext))]
    [Migration("20251119182354_InitialCreate_EntityConfiguration")]
    partial class InitialCreate_EntityConfiguration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("entity_configuration")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OnboardingApi.Domain.EntityConfiguration.Aggregates.EntityType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Icon")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("icon");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("entity_types", "entity_configuration");
                });

            modelBuilder.Entity("OnboardingApi.Domain.EntityConfiguration.Aggregates.EntityType", b =>
                {
                    b.OwnsMany("OnboardingApi.Domain.EntityConfiguration.Aggregates.EntityTypeRequirement", "Requirements", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<int>("DisplayOrder")
                                .HasColumnType("integer")
                                .HasColumnName("display_order");

                            b1.Property<Guid>("EntityTypeId")
                                .HasColumnType("uuid")
                                .HasColumnName("entity_type_id");

                            b1.Property<bool>("IsRequired")
                                .HasColumnType("boolean")
                                .HasColumnName("is_required");

                            b1.Property<Guid>("RequirementId")
                                .HasColumnType("uuid")
                                .HasColumnName("requirement_id");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at");

                            b1.HasKey("Id");

                            b1.HasIndex("EntityTypeId");

                            b1.ToTable("entity_type_requirements", "entity_configuration");

                            b1.WithOwner()
                                .HasForeignKey("EntityTypeId");
                        });

                    b.Navigation("Requirements");
                });
#pragma warning restore 612, 618
        }
    }
}
